version: '3.9'
services:
  react-app:
    build:
      context: ./node/
      dockerfile: Dockerfile.frontend
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd app && yarn start"
    ports:
      - "3000:3000"

  next-api:
    build:
      context: ./node/
      dockerfile: Dockerfile.backend
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd api && npm run dev"
    tty: true
    ports:
      - "8080:8080"
    environment:
      - WATCHPACK_POLLING=true

  mysql-db:
    build:
      context: ./mysql/
      dockerfile: Dockerfile.database
    volumes:
      - db-store:/var/lib/mysql
      - ./db/conf/my.conf:/ect/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  db-store: